### ISSUE TITLE
Issue building Cita,Cemu,Duckstation,PCSX2

### ISSUE THREAD

**Issue by HomelessCucumber** [V0rt3x667/ArchyPie-Setup#47]
Hello,
As per the title everything else installs but these packages for me. I've also tried installing packages individually in the setup but no dice. Citra/Cemu does create the build folder/files in tmp folder but returns an error that it could not be found; PCSX2 and Duckstation have a patch error.

Running on Endeavoros fully updated  + Hyprland

[rps_2024-01-02_221831.log](https://github.com/V0rt3x667/ArchyPie-Setup/files/13815574/rps_2024-01-02_221831.log)
[rps_2024-01-02_221858.log](https://github.com/V0rt3x667/ArchyPie-Setup/files/13815575/rps_2024-01-02_221858.log)
[rps_2024-01-02_221939.log](https://github.com/V0rt3x667/ArchyPie-Setup/files/13815576/rps_2024-01-02_221939.log)

**Comment by V0rt3x667** [comment]
Hi, thanks for reporting the issues. These emulators are always breaking I guess due to their rapid development cycles. I will take a look at the issues and get back to you.

**Comment by V0rt3x667** [comment]
Citra should be working again now. Please update the script and test. Thanks.

**Comment by V0rt3x667** [comment]
I tested Cemu and it appears to be working. Could you please test again?

**Comment by V0rt3x667** [comment]
Duckstation should be working again now. Please update the script and test. Thanks.

**Comment by HomelessCucumber** [comment]
Thanks for having a look really I appreciate it, Citra and Duckstation install for me now. Unfortunately Cemu still won't build, but I'm guessing it might be something on my end if it's building for you. Here's my log file after cleaning the source folder and rerunning it. Thanks again.
[rps_2024-01-03_205047.log](https://github.com/V0rt3x667/ArchyPie-Setup/files/13824961/rps_2024-01-03_205047.log)

**Comment by V0rt3x667** [comment]
If you run `cat /usr/lib/cmake/glm/glmConfig.cmake ` in a terminal do you have the following line in the output:
`set_and_check(GLM_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include")`

Thanks

**Comment by V0rt3x667** [comment]
I have fixed PCSX2 if you would like to test it. Thanks.

**Comment by HomelessCucumber** [comment]
Tested out the newest script and PCSX2 builds, you're a wizard. I also changed to glm-git from extra and CEMU is good to go on my end. Thank you so much!
